// <auto-generated />
using System;
using KineticTrack.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KineticTrack.Infrastructure.Migrations
{
    [DbContext(typeof(KineticTrackDbContext))]
    [Migration("20260621192826_RenameCabinetRoleEnumValues")]
    partial class RenameCabinetRoleEnumValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KineticTrack.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("activity_log_id");

                    b.Property<string>("EvaMetric")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("eva_metric");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("execution_date");

                    b.Property<Guid>("ExerciseLibraryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_library_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<string>("PatientComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("patient_comment");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<string>("PractitionerNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("practitioner_note");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("protocol_id");

                    b.HasKey("ActivityLogId")
                        .HasName("pk_activity_log");

                    b.HasIndex("ExerciseLibraryId")
                        .HasDatabaseName("ix_activity_log_exercise_library_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_activity_log_patient_id");

                    b.HasIndex("ProtocolId")
                        .HasDatabaseName("ix_activity_log_protocol_id");

                    b.ToTable("ACTIVITY_LOG", (string)null);
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Cabinet", b =>
                {
                    b.Property<Guid>("CabinetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cabinet_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("CabinetId")
                        .HasName("pk_cabinet");

                    b.ToTable("CABINET", (string)null);

                    b.HasData(
                        new
                        {
                            CabinetId = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            Address = "Rue de la Santé 1, 6000 Charleroi",
                            Name = "Cabinet KineticTrack"
                        });
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.CabinetMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cabinet_id");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit")
                        .HasColumnName("is_owner");

                    b.Property<string>("RoleAtCabinet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_at_cabinet");

                    b.HasKey("UserId", "CabinetId")
                        .HasName("pk_cabinet_member");

                    b.HasIndex("CabinetId")
                        .HasDatabaseName("ix_cabinet_member_cabinet_id");

                    b.ToTable("CABINET_MEMBER", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            CabinetId = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            IsOwner = true,
                            RoleAtCabinet = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            CabinetId = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            IsOwner = false,
                            RoleAtCabinet = "Secretary"
                        });
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.CareEpisode", b =>
                {
                    b.Property<Guid>("CareEpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("care_episode_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("title");

                    b.HasKey("CareEpisodeId")
                        .HasName("pk_care_episode");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_care_episode_patient_id");

                    b.ToTable("CARE_EPISODE", (string)null);
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.ExerciseLibrary", b =>
                {
                    b.Property<Guid>("ExerciseLibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_library_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("media_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("name");

                    b.HasKey("ExerciseLibraryId")
                        .HasName("pk_exercise_library");

                    b.ToTable("EXERCISE_LIBRARY", (string)null);
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("MedicalHistory")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medical_history");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("PatientId")
                        .HasName("pk_patients");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_user_id");

                    b.ToTable("PATIENTS", (string)null);
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Practitioner", b =>
                {
                    b.Property<Guid>("PractitionerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("license_number");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("speciality");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("PractitionerId")
                        .HasName("pk_practitioners");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_practitioners_user_id");

                    b.ToTable("PRACTITIONERS", (string)null);
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Protocol", b =>
                {
                    b.Property<Guid>("ProtocolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("protocol_id");

                    b.Property<Guid>("CareEpisodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("care_episode_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title");

                    b.HasKey("ProtocolId")
                        .HasName("pk_protocol");

                    b.HasIndex("CareEpisodeId")
                        .HasDatabaseName("ix_protocol_care_episode_id");

                    b.ToTable("PROTOCOL", (string)null);
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.ProtocolExercise", b =>
                {
                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("protocol_id");

                    b.Property<Guid>("ExerciseLibraryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_library_id");

                    b.Property<string>("Order")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("order");

                    b.Property<string>("Parameters")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("parameters");

                    b.HasKey("ProtocolId", "ExerciseLibraryId")
                        .HasName("pk_protocol_exercise");

                    b.HasIndex("ExerciseLibraryId")
                        .HasDatabaseName("ix_protocol_exercise_exercise_library_id");

                    b.ToTable("PROTOCOL_EXERCISE", (string)null);
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPasswordChanged")
                        .HasColumnType("bit")
                        .HasColumnName("is_password_changed");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("USERS", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 6, 4, 10, 9, 27, 355, DateTimeKind.Utc),
                            Email = "admin@kinetictrack.be",
                            Firstname = "Admin",
                            IsActive = true,
                            IsDeleted = false,
                            IsPasswordChanged = true,
                            Lastname = "KineticTrack",
                            PasswordHash = "aVZ5lhmja/hC7/cO/dMYWYOGfWYzFH4Is4X2UAazw9GRGBDCaaBdKcHUYP3TtXKo"
                        },
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 6, 4, 10, 9, 27, 355, DateTimeKind.Utc),
                            Email = "marie@kinetictrack.be",
                            Firstname = "Marie",
                            IsActive = true,
                            IsDeleted = false,
                            IsPasswordChanged = true,
                            Lastname = "Secrétaire",
                            PasswordHash = "aVZ5lhmja/hC7/cO/dMYWYOGfWYzFH4Is4X2UAazw9GRGBDCaaBdKcHUYP3TtXKo"
                        });
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("KineticTrack.Domain.Entities.ExerciseLibrary", "Exercise")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ExerciseLibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_log_exercise_libraries_exercise_library_id");

                    b.HasOne("KineticTrack.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_log_patients_patient_id");

                    b.HasOne("KineticTrack.Domain.Entities.Protocol", "Protocol")
                        .WithMany()
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_log_protocols_protocol_id");

                    b.Navigation("Exercise");

                    b.Navigation("Patient");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.CabinetMember", b =>
                {
                    b.HasOne("KineticTrack.Domain.Entities.Cabinet", "Cabinet")
                        .WithMany("Members")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_cabinet_member_cabinet_cabinet_id");

                    b.HasOne("KineticTrack.Domain.Entities.User", "User")
                        .WithMany("CabinetMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cabinet_member_users_user_id");

                    b.Navigation("Cabinet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.CareEpisode", b =>
                {
                    b.HasOne("KineticTrack.Domain.Entities.Patient", "Patient")
                        .WithMany("CareEpisodes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_care_episode_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Patient", b =>
                {
                    b.HasOne("KineticTrack.Domain.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("KineticTrack.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patients_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Practitioner", b =>
                {
                    b.HasOne("KineticTrack.Domain.Entities.User", "User")
                        .WithOne("Practitioner")
                        .HasForeignKey("KineticTrack.Domain.Entities.Practitioner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practitioners_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Protocol", b =>
                {
                    b.HasOne("KineticTrack.Domain.Entities.CareEpisode", "CareEpisode")
                        .WithMany("Protocols")
                        .HasForeignKey("CareEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_protocol_care_episode_care_episode_id");

                    b.Navigation("CareEpisode");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.ProtocolExercise", b =>
                {
                    b.HasOne("KineticTrack.Domain.Entities.ExerciseLibrary", "Exercise")
                        .WithMany("ProtocolExercises")
                        .HasForeignKey("ExerciseLibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_protocol_exercise_exercise_library_exercise_library_id");

                    b.HasOne("KineticTrack.Domain.Entities.Protocol", "Protocol")
                        .WithMany("ProtocolExercises")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_protocol_exercise_protocol_protocol_id");

                    b.Navigation("Exercise");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Cabinet", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.CareEpisode", b =>
                {
                    b.Navigation("Protocols");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.ExerciseLibrary", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("ProtocolExercises");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Patient", b =>
                {
                    b.Navigation("CareEpisodes");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.Protocol", b =>
                {
                    b.Navigation("ProtocolExercises");
                });

            modelBuilder.Entity("KineticTrack.Domain.Entities.User", b =>
                {
                    b.Navigation("CabinetMemberships");

                    b.Navigation("Patient");

                    b.Navigation("Practitioner");
                });
#pragma warning restore 612, 618
        }
    }
}
